import cython
import enum

class R8(enum.IntEnum):
    B = 0
    C = 1
    D = 2
    E = 3
    H = 4
    L = 5
    HL_DREF = 6
    A = 7

class R16(enum.IntEnum):
    BC = 0
    DE = 1
    HL = 2
    SP = 3

class GB_State:
    def __cinit__(self) -> None: ...
    def __dealloc__(self) -> None: ...
    def set_r8(self, reg: R8, val: cython.uint): ...
    def get_r8(self, reg: R8) -> cython.uint: ...
    def set_f(self, val: cython.uint): ...
    def get_f(self) -> cython.uint: ...
    def set_pc(self, val: cython.uint): ...
    def get_pc(self) -> cython.uint: ...
    def set_r16(self, reg: R16, val: cython.uint): ...
    def get_r16(self, reg: R16) -> cython.uint: ...
    def set_ime(self, val: bool): ...
    def get_ime(self) -> bool: ...
    def read_mem8(self, addr: cython.uint) -> cython.uint: ...
    def write_mem8(self, addr: cython.uint, val: cython.uint): ...
    def fetch_and_exec(self) -> None: ...
    def get_err(self) -> bool: ...
    def use_flat_mem(self, enabled: bool): ...
