on:
  push:
    branches:
    - '**'
jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - run: |
          docker run -i \
            --mount=type=bind,source=$PWD,destination=/gb_emu \
            --entrypoint=/gb_emu/scripts/run_tests_ubuntu26_04.sh \
            ubuntu:26.04
